export const AllItems = [
    //'Choice Band',
    //'Choice Scarf',
    //'Choice Specs',
    //'Eviolite',
    //'Expert Belt',
    //'Focus Sash',
    //'Heavy-Duty Boots',
    //'Life Orb',
    //'Mental Herb',
    //'Power Herb',
    //'Salac Berry',
    // TODO
    "absolite", "absorb-bulb", "adrenaline-orb", "aerodactylite", "air-balloon", "alakazite",
    "altarianite", "ampharosite", "apicot-berry", "aspear-berry", "audinite",
    "babiri-berry", "banettite", "beedrillite", "big-root", "binding-band", "black-belt",
    "black-glasses", "blunder-policy", "bright-powder", "bug-gem", "burn-drive", "cameruptite",
    "cell-battery", "charcoal", "charti-berry", "cheri-berry", "chesto-berry", "chilan-berry",
    "chill-drive", "choice-band", "choice-scarf", "choice-specs", "chople-berry",
    "coba-berry", "colbur-berry", "custap-berry", "damp-rock", "dark-gem", "deep-sea-scale",
    "deep-sea-tooth", "destiny-knot", "douse-drive", "draco-plate", "dragon-fang", "dragon-gem",
    "dread-plate", "earth-plate", "eject-button", "eject-pack", "electric-gem", "electric-seed",
    "eviolite", "expert-belt", "fairy-gem", "fighting-gem", "fire-gem", "fist-plate",
    "flame-orb", "flame-plate", "float-stone", "flying-gem", "focus-band", "focus-sash",
    "full-incense", "galladite", "ganlon-berry", "gardevoirite", "gengarite", "ghost-gem",
    "glalitite", "grass-gem", "grassy-seed", "grip-claw", "ground-gem", "haban-berry",
    "hard-stone", "heat-rock", "heavy-duty-boots", "heracronite", "houndoominite", "ice-gem",
    "icicle-plate", "icy-rock", "insect-plate", "iron-ball", "iron-plate", "jaboca-berry",
    "kasib-berry", "kebia-berry", "kee-berry", "kings-rock", "lagging-tail", "lansat-berry",
    "lax-incense", "leppa-berry", "liechi-berry", "life-orb", "light-ball", "light-clay",
    "lopunnite", "lucky-punch", "lum-berry", "luminous-moss", "magnet",
    "manectite", "maranga-berry", "meadow-plate", "mental-herb", "metal-coat", "metal-powder",
    "metronome", "micle-berry", "mind-plate", "miracle-seed", "misty-seed", "muscle-band",
    "mystic-water", "never-melt-ice", "normal-gem", "normalium-z", "occa-berry", "odd-incense",
    "passho-berry", "payapa-berry", "pecha-berry", "persim-berry", "petaya-berry", "pidgeotite",
    "pinsirite", "pixie-plate", "poison-barb", "poison-gem", "power-herb", "protective-pads",
    "psychic-gem", "psychic-seed", "quick-claw", "quick-powder", "rawst-berry", "red-card",
    "rindo-berry", "ring-target", "rock-gem", "rock-incense", "room-service", "rose-incense",
    "roseli-berry", "rowap-berry", "rusted-shield", "rusted-sword", "sablenite", "safety-goggles",
    "salac-berry", "scope-lens", "sea-incense", "sharp-beak", "sharpedonite", "shed-shell",
    "shock-drive", "shuca-berry", "silk-scarf", "silver-powder", "sky-plate", "slowbronite",
    "smoke-ball", "smooth-rock", "snowball", "soft-sand", "spell-tag", "splash-plate",
    "spooky-plate", "starf-berry", "steel-gem", "stick", "sticky-barb", "stone-plate",
    "tanga-berry", "terrain-extender", "thick-club", "throat-spray", "toxic-orb", "toxic-plate",
    "twisted-spoon", "utility-umbrella", "venusaurite", "wacan-berry", "water-gem", "wave-incense",
    "weakness-policy", "white-herb", "wide-lens", "wise-glasses", "yache-berry", "zap-plate", "zoom-lens"
];