name: Deploy
on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare Workers
    if: github.ref == 'refs/heads/main'
    env:
      CF_ACCOUNT_ID: "${{ secrets.CF_ACCOUNT_ID }}"
      CF_API_TOKEN: "${{ secrets.CF_API_TOKEN }}"
      CF_ZONE_ID: "${{ secrets.CF_ZONE_ID }}"
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v13
        name: "Install flake-capable Nix"
        with:
          install_url: https://nixos-nix-install-tests.cachix.org/serve/i6laym9jw3wg9mw6ncyrk6gjx4l34vvx/install
          install_options: '--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve'
          extra_nix_config: |
            experimental-features = nix-command flakes
      - uses: cachix/cachix-action@v10
        with:
          name: moosingin3space
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: mkdir dist
      - run: nix develop -c wrangler publish
        name: Build and deploy worker